### ISSUE TITLE
斗鱼有问题了

### ISSUE THREAD

**Issue by thep0y** [wbt5/real-url#136]
```shell
输入斗鱼直播间号：
88883
Traceback (most recent call last):
  File "douyu.py", line 122, in <module>
    print(s.get_real_url())
  File "douyu.py", line 115, in get_real_url
    key = self.get_js()
  File "douyu.py", line 58, in get_js
    res = js.call('ub98484234')
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/site-packages/execjs/_external_runtime.py", line 159, in _extract_result
    ret = json.loads(output_last_line)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/thepoy/miniconda3/envs/temp/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wbt5** [comment]
感谢反馈，特殊房间号的直播间，待修复
