### ISSUE TITLE
斗鱼已失效那位大佬破解一下

### ISSUE THREAD

**Issue by q448159774** [wbt5/real-url#185]
斗鱼已失效那位大佬破解一下

**Comment by moozik** [comment]
我好像找到新接口了，我试一下

**Comment by q448159774** [comment]
> 我好像找到新接口了，我试一下

可以的，等 你 好消息，，

**Comment by moozik** [comment]
> > 我好像找到新接口了，我试一下
> 
> 可以的，等 你 好消息，，

提了，新连接变长了，不知道还有没有简洁的链接

**Comment by q448159774** [comment]
> > > 我好像找到新接口了，我试一下
> > 
> > 
> > 可以的，等 你 好消息，，
> 
> 提了，新连接变长了，不知道还有没有简洁的链接

老哥，斗鱼新的代码提一下吧

**Comment by moozik** [comment]
你要不在这个代码库等owner合我提的分支,要不去我拉的代码库找

**Comment by wbt5** [comment]
应该是拼接 `http://tx2play1.douyucdn.cn` 主机已经失效了，用返回结果中的完整链接应该可以播。
感谢老哥贡献代码

**Comment by q448159774** [comment]
> 你要不在这个代码库等owner合我提的分支,要不去我拉的代码库找

Traceback (most recent call last):
  File "douyu.py", line 133, in <module>
    print(s.get_real_url())
  File "douyu.py", line 113, in get_real_url
    error, url = self.get_pre()
  File "douyu.py", line 54, in get_pre
    return error, data['rtmp_url'] + '/' + data['rtmp_live']
TypeError: string indices must be integers
---------------------------------
拉了你代码 报这个错误 是python版本的问题？？

**Comment by q448159774** [comment]
> 你要不在这个代码库等owner合我提的分支,要不去我拉的代码库找
  res = self.s.post(url, headers=headers, data=data).json()
返回：{'error': 742017, 'msg': '后端服务异常', 'data': ''}

**Comment by q448159774** [comment]
> 应该是拼接 `http://tx2play1.douyucdn.cn` 主机已经失效了，用返回结果中的完整链接应该可以播。
> 感谢老哥贡献代码

作者你的项目更新了？？？

**Comment by wbt5** [comment]
> > 应该是拼接 `http://tx2play1.douyucdn.cn` 主机已经失效了，用返回结果中的完整链接应该可以播。
> > 感谢老哥贡献代码
> 
> 作者你的项目更新了？？？

暂未更新，等抽时间push代码

**Comment by q448159774** [comment]
> > > 应该是拼接 `http://tx2play1.douyucdn.cn` 主机已经失效了，用返回结果中的完整链接应该可以播。
> > > 感谢老哥贡献代码
> > 
> > 
> > 作者你的项目更新了？？？
> 
> 暂未更新，等抽时间push代码

好的， 麻烦有时间更新一下，感谢@moozik 感谢作者

**Comment by wjxgzz** [comment]
hls3-akm.douyucdn.cn
hlsa-akm.douyucdn.cn
hls1a-akm.douyucdn.cn

3个墙外不用带尾巴的akm cdn

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
dyscdnali1.douyucdn.cn
dyscdnali3.douyucdn.cn

2个阿里的

**Comment by zqs125** [comment]
@wbt5 你提交的最新斗鱼代码，经测试依然是无效的，能获取到地址，但只能播放2秒钟

**Comment by vigidroid** [comment]
@4bbu6j5885o3gpv6ss8 亲测可用。能教一下怎么找到这种链接吗，想学习

**Comment by qq2225936589** [comment]
目前最新代码返回的是m3u8, URL字符串中m3u8替换成 flv 就而已流畅播放了。

**Comment by li-xiaog** [comment]
@wjxgzz  @4bbu6j5885o3gpv6ss8 两位大佬是咋找到的

**Comment by ixinshang** [comment]
> hls3-akm.douyucdn.cn
> hlsa-akm.douyucdn.cn
> hls1a-akm.douyucdn.cn
> 
> 3个墙外不用带尾巴的akm cdn

恩山大佬？ @wjxgzz

**Comment by wbt5** [comment]
@wjxgzz @4bbu6j5885o3gpv6ss8 两位大佬牛啊🐂

**Comment by FedoraLinux1** [comment]
> > -_-|| 那些cdn 好像今天失效了
> 
> 我试了下，还是可以用的啊

可能是我dns污了，全重置后，不太行，换了@wjxgzz大佬的方法OK了

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
昨天发现上面的502不知到能恢复否
找到一个新的
[akm-tct.douyucdn.cn](http://akm-tct.douyucdn.cn/)

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
akm-tct.douyucdn.cn  今天用着不知道为什么容易卡 又找了找
更新今天(3-29)发现的
vplay1a.douyucdn.cn
vplay3a.douyucdn.cn

**Comment by yuaaanok** [comment]
> akm-tct.douyucdn.cn 今天用着不知道为什么容易卡 又找了找 更新今天(3-29)发现的 vplay1a.douyucdn.cn vplay3a.douyucdn.cn

兄弟能说下是怎么找的吗

**Comment by dingzhengjie** [comment]
> > -_-|| 那些cdn 好像今天失效了
> 
> 
> 
> `http://552725f8e38d89f6e65d4e7a9f9fb0c0.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://c5510a3199607585fb44295ca4694e16.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://39936a135441e1f119e6c5ebb34591d0.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://c69c50e0e803d0c223429122c7fe29e2.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://78487ddb5728669970968ef4095a2032.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://e59abdd420c65d43cc1550d493a88c71.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://0a51b2899cace1631c0416ae55c6df56.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://3bfe08a90a81fe93921c3668145b7414.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://e3ab1234e9ca74d2ee6ed4374eb9a834.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://6133dcd84e56fb1496c230da1fdc9bd6.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://0eb4b285c52a1546b8143b69bee9f39b.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://a8d150f4d487055366f0498573257e3f.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://dd1d351d3d60d116f0cccbe62fc061cb.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> http://cb195d4736c83b7807b0b293644f0e1e.v.smtcdns.net/hlstct.douyucdn2.cn/dyliveflv3/426517rbUPr2Gpe7.m3u8
> 
> `
> 
> 最简单粗暴的http://CDN/主机名/尾巴

这个咋实现的

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
[vplay1a.douyucdn.cn]
[vplay3a.douyucdn.cn]
昨天玩些时间发现挂了 ,太困了睡觉. 今天起来找了一会
xs flv 发现后缀可以通用
一个是之前的akm-tct.douyucdn.cn提过的还能用 发现也不卡了
ws-tct.douyucdn.cn(这个好像是就近的CDN)

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
又挂了新的
hw-tct.douyucdn.cn

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
更新
hdltc1.douyucdn.cn 
hdltctwk.douyucdn2.cn

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
更新有点频繁
openhls-tct.douyucdn2.cn

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
加尾巴了换头应该不行,等更新

**Comment by EvinceMoi** [comment]
openflv-huos.douyucdn2.cn

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
> [openflv-huos.douyucdn2.cn](http://openflv-huos.douyucdn2.cn)

感谢  !  大神

**Comment by HelloGitHubWeb** [comment]
大哥们太牛逼了 能不能帮我搞个B站的直播源啊 谢谢大哥们

**Comment by jinghao-666** [comment]
> openflv-huos.douyucdn2.cn

形式http://openflv-huos.douyucdn2.cn/live/{key}.flv 格式

**Comment by jinghao-666** [comment]
> 大哥们太牛逼了 能不能帮我搞个B站的直播源啊 谢谢大哥们

https://junlong.plus/ztool/live 可以来这块试试。参考https://github.com/wbt5/real-url/issues/184#issuecomment-853847581

**Comment by jinghao-666** [comment]
> 更新有点频繁 openhls-tct.douyucdn2.cn

请问这种cdn可以在哪里找到

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
新  dyp2p-huos.douyucdn2.cn    尾巴现在m3u8    flv   xs 试验失败

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
> > 大哥们太牛逼了 能不能帮我搞个B站的直播源啊 谢谢大哥们
> 
> https://junlong.plus/ztool/live 可以来这块试试。参考[#184 (comment)](https://github.com/wbt5/real-url/issues/184#issuecomment-853847581)

b 站可以用  streamlink

**Comment by HelloGitHubWeb** [comment]
streamlink我改如何使用

**Comment by HelloGitHubWeb** [comment]
> > > 大哥们太牛逼了 能不能帮我搞个B站的直播源啊 谢谢大哥们
> > 
> > 
> > https://junlong.plus/ztool/live 可以来这块试试。参考[#184 (comment)](https://github.com/wbt5/real-url/issues/184#issuecomment-853847581)
> 
> b 站可以用 streamlink

streamlink我改如何使用

**Comment by asd2822613** [comment]
> 新 dyp2p-huos.douyucdn2.cn 尾巴现在m3u8 flv xs 试验失败

大哥还有新的flv不

**Comment by HelloGitHubWeb** [comment]
> 新 dyp2p-huos.douyucdn2.cn 尾巴现在m3u8 flv xs 试验失败

m3u8需要缓存 感觉不太好用

**Comment by li-xiaog** [comment]
放弃使用cdn了  就用斗鱼接口返回的url了

**Comment by HelloGitHubWeb** [comment]
twitch怎么获取源啊

**Comment by HelloGitHubWeb** [comment]
最近想看国外瓦罗兰特

**Comment by wjxgzz** [comment]
https://tc-tc2-interact.douyucdn2.cn/dyliveflv1/36252rt3pSdsXfdT.m3u8

**Comment by wjxgzz** [comment]
https://tc-tc2-interact.douyucdn2.cn/dyliveflv1/36252rt3pSdsXfdT.m3u8
