### ISSUE TITLE
斗鱼获取链接有问题

### ISSUE THREAD

**Issue by AlterGu** [wbt5/real-url#200]
Traceback (most recent call last):
  File ".\douyu.py", line 116, in <module>
    print(s.get_real_url())
  File ".\douyu.py", line 105, in get_real_url
    ret.append(self.get_pre())
  File ".\douyu.py", line 51, in get_pre
    return data['rtmp_url'] + '/' + data['rtmp_live']
KeyError: 'rtmp_url'

**Comment by AlterGu** [comment]
使用的是最新版本的仓库代码

**Comment by gtrvirgo** [comment]
#196 在douyu.py51行return之前添加
`data = res['data']`

**Comment by AlterGu** [comment]
添加后又有报错


![image](https://user-images.githubusercontent.com/39581263/121773243-2bd39780-cbad-11eb-923f-2786f752f6fc.png)


输入斗鱼直播间号：
787747
输入画质(1流畅；2高清；3超清；4蓝光4M；0蓝光8M或10M)：
4
Traceback (most recent call last):
  File "g:/Project/Pyhton/real-url/douyu.py", line 116, in <module>
    print(s.get_real_url())
  File "g:/Project/Pyhton/real-url/douyu.py", line 106, in get_real_url
    ret.append(self.get_js())
  File "g:/Project/Pyhton/real-url/douyu.py", line 70, in get_js
    return res['url']
TypeError: string indices must be integers

**Comment by wbt5** [comment]
建议拉取最新代码

合并问题 Duplicate of #185

**Comment by AlterGu** [comment]
谢谢, 已解决
