### ISSUE TITLE
你好呀，那个tiktok反馈失效帮忙看一下

### ISSUE THREAD

**Issue by zsray** [wbt5/real-url#293]
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======= RESTART: C:\Users\Administrator\Desktop\real-url-master\tiktok.py ======
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\real-url-master\tiktok.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
>>>

**Comment by Dauth** [comment]
> Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license()" for more information.
> 
> > > >
> 
> ======= RESTART: C:\Users\Administrator\Desktop\real-url-master\tiktok.py ====== Traceback (most recent call last): File "C:\Users\Administrator\Desktop\real-url-master\tiktok.py", line 9, in import requests ModuleNotFoundError: No module named 'requests'
> 
> > > >

https://stackoverflow.com/a/17309309
