### ISSUE TITLE
wbt5大佬还在不？虎牙的失效了，有木有计划修复一下啊

### ISSUE THREAD

**Issue by iancsy** [wbt5/real-url#360]
获取的地址已经无法打开了

**Comment by zheyiyuezhuo** [comment]
我也是，获得的链接无法播放以及无法下载，下载只是下载一段的，是不是获取的链接加了时间限制啥的

**Comment by dingzhengjie** [comment]
#331

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
没想到会轮的到小白解答   测试后连接 能播放一段  证明还能用  似着净化了部分参数就可以了
real_url = re.findall(r'^(.*?)\&ctype',real_url)[0]
print(real_url)

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
发现一些直播间是  .slice 切片的格式不能解码播放  等大佬搞定

**Comment by zheyiyuezhuo** [comment]
> 没想到会轮的到小白解答 测试后连接 能播放一段 证明还能用 似着净化了部分参数就可以了 real_url = re.findall(r'^(.*?)&ctype',real_url)[0] print(real_url)

这个是直接修改huya.py最后几行，把 `get_real_url(rid)` 修改为 `re.findall(r'^(.*?)&ctype',real_url)[0]` 吗？
我修改好以后运行提示错误，错误代码如下，还是说我改的不对

```sh
Traceback (most recent call last):
  File "E:\Download\GitHub\real-url\huya.py", line 56, in <module>
    real_url = re.findall(r'^(.*?)&ctype',real_url)[0]
NameError: name 'real_url' is not defined
```

**Comment by Icarusradio** [comment]
> > 没想到会轮的到小白解答 测试后连接 能播放一段 证明还能用 似着净化了部分参数就可以了 real_url = re.findall(r'^(.*?)&ctype',real_url)[0] print(real_url)
> 
> 这个是直接修改huya.py最后几行，把 `get_real_url(rid)` 修改为 `re.findall(r'^(.*?)&ctype',real_url)[0]` 吗？ 我修改好以后运行提示错误，错误代码如下，还是说我改的不对
> 
> ```shell
> Traceback (most recent call last):
>   File "E:\Download\GitHub\real-url\huya.py", line 56, in <module>
>     real_url = re.findall(r'^(.*?)&ctype',real_url)[0]
> NameError: name 'real_url' is not defined
> ```

不是的，是在下面加一行
```python
real_url = get_real_url(rid)
real_url = re.findall(r'^(.*?)&ctype',real_url)[0]
print('该直播间源地址为：')
print(real_url)
```

**Comment by Xmarmalade** [comment]
现在又失效了，获取到的 .flv 只有一段 .m3u8直接403
