### ISSUE TITLE
斗鱼已经不能用了

### ISSUE THREAD

**Issue by thep0y** [wbt5/real-url#37]
```shell
请输入斗鱼数字房间号：2222
Traceback (most recent call last):
  File "./douyu.py", line 142, in <module>
    real_url = get_real_url(rid)
  File "./douyu.py", line 120, in get_real_url
    real_url = get_sign_url(tt[2], real_rid, tt[0], homejs)
  File "./douyu.py", line 82, in get_sign_url
    sign = get_sign(rid, post_v, tt, ub9)
  File "./douyu.py", line 36, in get_sign
    docjs = execjs.compile(ub9)
  File "/home/thepoy/miniconda3/envs/others/lib/python3.7/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/home/thepoy/miniconda3/envs/others/lib/python3.7/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/home/thepoy/miniconda3/envs/others/lib/python3.7/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.
```

**Comment by wbt5** [comment]
缺少JavaScript 运行环境，建议安装nodejs
