### ISSUE TITLE
快手一直显示直播间不存在或未开播,抓弹幕也不能用

### ISSUE THREAD

**Issue by h616311501** [wbt5/real-url#452]
在网页版复制ID后输入快手房间ID,一直显示直播间不存在或未开播

**Comment by h616311501** [comment]
如果是抓取弹幕,则显示
C:\Users\1\Downloads\real-url-master\real-url-master\danmu>python main.py
请输入直播间地址：
https://live.kuaishou.com/u/QD6666865
Traceback (most recent call last):
  File "C:\Users\1\Downloads\real-url-master\real-url-master\danmu\main.py", line 24, in <module>
    asyncio.run(main(a))
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\1\Downloads\real-url-master\real-url-master\danmu\main.py", line 20, in main
    await dmc.start()
  File "C:\Users\1\Downloads\real-url-master\real-url-master\danmu\danmaku\__init__.py", line 224, in start
    await self.init_ws()
  File "C:\Users\1\Downloads\real-url-master\real-url-master\danmu\danmaku\__init__.py", line 71, in init_ws
    ws_url, reg_datas = await self.__site.get_ws_info(self.__url)
  File "C:\Users\1\Downloads\real-url-master\real-url-master\danmu\danmaku\kuaishou.py", line 39, in get_ws_info
    raise Exception('找不到 wsFeedInfo，可能链接错误或 Cookie 过期')
Exception: 找不到 wsFeedInfo，可能链接错误或 Cookie 过期
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001FA574D1720>
