### ISSUE TITLE
红人直播：https://www.hongle.tv/　不能用了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#64]
python hongle.py
输入红人直播房间号：
101816913
Traceback (most recent call last):
  File "hongle.py", line 43, in <module>
    print(hongle(r))
  File "hongle.py", line 36, in hongle
    raise Exception('房间不存在')
Exception: 房间不存在

**Comment by wbt5** [comment]
感谢反馈，稍后更新。
