### ISSUE TITLE
运行main.py  No module named 'danmaku.yy'

### ISSUE THREAD

**Issue by cheshi666666** [wbt5/real-url#92]
Traceback (most recent call last):
  File "D:\Warcraft III\idm\real-url-master\danmu\main.py", line 6, in <module>
    import danmaku
  File "D:\Warcraft III\idm\real-url-master\danmu\danmaku\__init__.py", line 24, in <module>
    from .yy import YY
ModuleNotFoundError: No module named 'danmaku.yy'
什么原因呢 小白求救

**Comment by wbt5** [comment]
YY 弹幕的获取暂未实现哦，可以重新clone或注释掉yy相关代码
